// Code generated by the multiversx-sc multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           18
// Async Callback (empty):               1
// Total number of exported functions:  20

#![no_std]
#![feature(lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    staking
    (
        deposit_rewards
        stake
        stake_multiple
        calculateRewardsForUser
        claim_rewards
        unstake
        unstake_multiple
        getAdmin
        getStakingToken
        getRewardToken
        getRewardsAmount
        getTokensPerDay
        getUserStaking
        getStakedAddresses
        set_admin
        set_staking_token
        set_reward_token
        set_tokens_per_day
    )
}

multiversx_sc_wasm_adapter::empty_callback! {}
